refactoring

diff --git a/plugin/vmux b/plugin/vmux
--- a/plugin/vmux
+++ b/plugin/vmux
@@ -1,30 +1,36 @@
 #!/bin/sh
-session_prefix="vmux-session-"
-if [ $# -gt 0 ] && [ "$1" = list ]
-then
-  abduco -l | grep "$session_prefix"
-elif [ $# -gt 1 ] && [ "$1" = attach ]
-then
-  abduco -e '^g' -A "$2"
-elif [ $# -gt 0 ] && [ "$1" = new ]
-then
-  export EDITOR=vmux-editor
-  id=$(date +%s)-$2
-  server_file="/tmp/vim-server-$id"
-  session_name="$session_prefix$id"
-  if echo "$VMUX_EDITOR" | grep -v nvim >/dev/null
-  then
-    server_file="$session_name"
-    server_options="--servername $server_file"
-    vmux_server_file=$server_file abduco -e '^g' -A "$session_name" \
-                     $VMUX_EDITOR --cmd "let g:confirm_quit_nomap = 0" \
-                     --servername $server_file
-  else
-    vmux_server_file=$server_file abduco -e '^g' -A "$session_name" \
-                     $VMUX_EDITOR --cmd "let g:confirm_quit_nomap = 0" \
-                     --cmd "let g:server_addr = serverstart('$server_file')"
+
+check_conditions () {
+  if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
+    echo "You can't create and attach from inside neovim"
+    exit 1
   fi
-    
-else
-  echo "please provide an action (new|attach|list)"
-fi
+
+  if [ -z "$2" ]; then
+    echo "Provide second argument with session name"
+    exit 1
+  fi
+}
+
+case "$1" in
+  list)
+    abduco -l | awk '$NF ~ /^vmux-/ { gsub("vmux-", "", $NF); print($NF); }'
+    ;;
+  attach)
+    check_conditions $*
+    abduco -e '^g' -A "vmux-$2"
+    ;;
+  new)
+    check_conditions $*
+    export EDITOR=vmux-editor
+    export NVIM_LISTEN_ADDRESS=/tmp/vmux-$2
+    abduco -e '^g' -A "vmux-$2" vmux-editor
+    ;;
+  send)
+    check_conditions $*
+    export NVIM_LISTEN_ADDRESS=/tmp/vmux-$2
+    shift 2
+    nvr -s $*
+    ;;
+esac
+
